---
- hosts: windows
  tasks:
    - name: Remove existing ContosoWebApp folder
      win_shell: Remove-Item -Path "C:\\inetpub\\wwwroot\\ContosoWebApp" -Recurse -Force
      ignore_errors: yes

    - name: Remove existing artifacts folder
      win_shell: Remove-Item -Path "C:\\inetpub\\wwwroot\\artifacts" -Recurse -Force
      ignore_errors: yes

    - name: Extract ContosoWebApp.zip
      win_shell: Expand-Archive -Path C:\\jenkins\\workspace\\ContosoWebApp.zip -DestinationPath C:\\inetpub\\wwwroot

    - name: Convert ContosoWebApp folder to IIS WebApplication
      win_shell: ConvertTo-WebApplication -PSPath 'IIS:\\Sites\\Default Web Site\\ContosoWebApp'
